#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$ROOT/Config"
OUT="$ROOT/Config/LocalSigning.xcconfig"
KEYCHAIN="$CONFIG_DIR/TingMoLocalSigning.keychain-db"
IDENTITY="TingMo Local Development"
P12_PASSWORD="tingmo-local-signing"

mkdir -p "$CONFIG_DIR"

ensure_keychain_in_search_list() {
  local found="false"
  local keychain
  local keychains=()

  while IFS= read -r keychain; do
    keychain="${keychain#\"}"
    keychain="${keychain%\"}"
    [[ -z "$keychain" ]] && continue
    if [[ "$keychain" == "$KEYCHAIN" ]]; then
      found="true"
    fi
    keychains+=("$keychain")
  done < <(security list-keychains -d user | sed -E 's/^[[:space:]]+//')

  if [[ "$found" != "true" ]]; then
    security list-keychains -d user -s "$KEYCHAIN" "${keychains[@]}"
  fi
}

has_identity() {
  security find-identity -p codesigning -v "$KEYCHAIN" 2>/dev/null |
    grep -F "\"$IDENTITY\"" >/dev/null
}

if [[ ! -f "$KEYCHAIN" ]]; then
  security create-keychain -p "" "$KEYCHAIN"
fi

security unlock-keychain -p "" "$KEYCHAIN"
security set-keychain-settings -lut 21600 "$KEYCHAIN"
ensure_keychain_in_search_list

if ! has_identity; then
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "$tmpdir"' EXIT

  cat > "$tmpdir/openssl.cnf" <<EOF
[ req ]
distinguished_name = dn
x509_extensions = v3_req
prompt = no

[ dn ]
CN = $IDENTITY
O = TingMo
OU = Local Development

[ v3_req ]
basicConstraints = critical,CA:FALSE
keyUsage = critical,digitalSignature
extendedKeyUsage = critical,codeSigning
EOF

  openssl req \
    -newkey rsa:2048 \
    -nodes \
    -keyout "$tmpdir/key.pem" \
    -x509 \
    -days 3650 \
    -out "$tmpdir/cert.pem" \
    -config "$tmpdir/openssl.cnf" \
    -sha256 >/dev/null 2>&1

  if ! openssl pkcs12 \
    -legacy \
    -export \
    -out "$tmpdir/identity.p12" \
    -inkey "$tmpdir/key.pem" \
    -in "$tmpdir/cert.pem" \
    -name "$IDENTITY" \
    -passout "pass:$P12_PASSWORD" >/dev/null 2>&1; then
    openssl pkcs12 \
      -export \
      -out "$tmpdir/identity.p12" \
      -inkey "$tmpdir/key.pem" \
      -in "$tmpdir/cert.pem" \
      -name "$IDENTITY" \
      -passout "pass:$P12_PASSWORD" >/dev/null
  fi

  security import "$tmpdir/identity.p12" \
    -k "$KEYCHAIN" \
    -f pkcs12 \
    -P "$P12_PASSWORD" \
    -A \
    -T /usr/bin/codesign >/dev/null

  security add-trusted-cert \
    -r trustRoot \
    -p codeSign \
    -k "$KEYCHAIN" \
    "$tmpdir/cert.pem" >/dev/null
fi

if ! has_identity; then
  echo "Failed to create a valid local code-signing identity in $KEYCHAIN" >&2
  exit 1
fi

cat > "$OUT" <<EOF
// Generated by scripts/setup-local-signing.sh. Do not commit.
// Stable local signing prevents macOS TCC permissions from being tied to a
// different ad-hoc cdhash after every build.

CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = $IDENTITY
DEVELOPMENT_TEAM =
PROVISIONING_PROFILE_SPECIFIER =
OTHER_CODE_SIGN_FLAGS = --keychain \$(SRCROOT)/Config/TingMoLocalSigning.keychain-db
EOF

echo "Wrote $OUT"
echo "Using local signing keychain: $KEYCHAIN"
echo "Using signing identity: $IDENTITY"
